name: Build Vividl

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: windows-latest

    env:
      Solution_Name: Vividl.sln
      Depend_DownloadScript: Vividl\Lib\DownloadBinaries.ps1

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Add Path Devenv
      run: echo "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Install Microsoft Visual Studio Installer Projects
      shell: powershell
      run: |
        $url = 'https://marketplace.visualstudio.com/_apis/public/gallery/publishers/VisualStudioClient/vsextensions/MicrosoftVisualStudio2022InstallerProjects/2.0.0/vspackage'
        $path = 'C:\TEMP\InstallerProjects.vsix'
        Invoke-WebRequest -Uri $url -OutFile $path
        & 'C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\IDE\VSIXInstaller.exe' $path

    #- name: Add msbuild to PATH
    #  uses: microsoft/setup-msbuild@v1.1

    #- name: Setup MSVC
    #  uses: ilammy/msvc-dev-cmd@v1

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1

    - name: Restore NuGet packages
      run: nuget restore $env:Solution_Name

    - name: Download Depend Lib
      run: powershell -NoProfile -ExecutionPolicy Unrestricted ./Vividl\Lib\DownloadBinaries.ps1
      shell: cmd

    - name: Build Portable
      run: |
        devenv.com Vividl.sln /rebuild Publish-Portable

    - name: Build Installer
      run: |
        devenv.com Vividl.sln /rebuild Publish-Installer

    - name: Upload Portable exe
      uses: actions/upload-artifact@v3
      with:
        name: Vividl
        path: Vividl\bin\Portable\Vividl.exe

    - name: Upload Installer
      uses: actions/upload-artifact@v3
      with:
        name: VividlInstaller
        path: VividlSetup\Release\VividlSetup.msi