name: Build Vividl

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: windows-latest

    env:
      Solution_Name: Vividl.sln
      Depend_DownloadScript: Vividl\Lib\DownloadBinaries.ps1

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Add Path Devenv
      run: echo "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1

    - name: Restore NuGet packages
      run: nuget restore $env:Solution_Name

    - name: Download Depend Lib
      run: powershell -NoProfile -ExecutionPolicy Unrestricted ./Vividl\Lib\DownloadBinaries.ps1
      shell: cmd

    - name: Build Portable
      run: |
        devenv.com Vividl.sln /build Publish-Portable

    - name: Build Installer
      run: |
        devenv.com Vividl.sln /build Publish-Installer

    - name: Upload Portable exe
      uses: actions/upload-artifact@v3
      with:
        name: Vividl
        path: Vividl\bin\Portable\Vividl.exe

    - name: Upload Installer
      uses: actions/upload-artifact@v3
      with:
        name: VividlInstaller
        path: VividlSetup\Release\VividlSetup.msi