name: Build Vividl

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release, Publish-Install, Publish-Portable]
        #build_type : [Publish-Install, Publish-Portable]
        #dotnet-version: ['4.8.0', '6.0.14' ]

    runs-on: windows-latest  # For a list of available runner types, refer to
                            # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: Vividl.sln                          # Replace with your solution name, i.e. MyWpfApp.sln.
      SetupProject_Name: VividlSetup\VividlSetup.vdproj
      Depend_DownloadScript: Vividl\Lib\DownloadBinaries.ps1
      DEVENV_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.com

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Set up MSVC environment
      run: |
        "C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1

    - name: Restore NuGet packages
      run: nuget restore $env:Solution_Name

    - name: Download Depend Lib
      run: powershell -NoProfile -ExecutionPolicy Unrestricted ./Vividl\Lib\DownloadBinaries.ps1
      shell: cmd

    - name: Devenv Build
      run: |
        "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.com"Vividl.sln /build '${{ matrix.configuration }}'
